#!/bin/bash

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

# Install the dotfiles I want
cp -r dotfiles.codespaces $HOME/.dotfiles.codespaces
if [[ -z "$PAT_TOKEN" ]]
then
  # check if https://github.com/${GITHUB_USER}/dotfiles.git exists
  if git ls-remote --exit-code https://${GITHUB_USER}:${PAT_TOKEN}@github.com/${GITHUB_USER}/dotfiles.git > /dev/null 2>&1; then
    git clone --depth 1 --recurse-submodules --shallow-submodules https://${GITHUB_USER}:${PAT_TOKEN}@github.com/${GITHUB_USER}/dotfiles.git $HOME/.dotfiles
  fi
else
  if git ls-remote --exit-code https://github.com/${GITHUB_USER}/dotfiles.git > /dev/null 2>&1; then
    git clone https://github.com/${GITHUB_USER}/dotfiles.git $HOME/.dotfiles
  fi
fi

# Do the rest of the tasks from the home dir
cd $HOME

# create bindir
mkdir -p $HOME/bin

# A bit of a hack
mv .gitconfig .gitconfig.private
mv .bashrc .bashrc.dist
mv .zshrc .zshrc.dist
$HOME/.dotfiles.codespaces/bin/dotfiles.symlink install

echo "Setting shell to zsh"
sudo chsh -s /usr/bin/zsh $USER

# Install fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all

PATH=${PATH}:/opt/nvim/bin/
