#!/bin/bash

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

# Install the dotfiles I want
cp -r dotfiles.codespaces $HOME/.dotfiles.codespaces
if [[ -z "$PAT_TOKEN" ]]
then
  # check if https://github.com/${GITHUB_USER}/dotfiles.git exists
  if git ls-remote --exit-code https://${GITHUB_USER}:${PAT_TOKEN}@github.com/${GITHUB_USER}/dotfiles.git > /dev/null 2>&1; then
    git clone --depth 1 --recurse-submodules --shallow-submodules https://${GITHUB_USER}:${PAT_TOKEN}@github.com/${GITHUB_USER}/dotfiles.git $HOME/.dotfiles
  fi
else
  if git ls-remote --exit-code https://github.com/${GITHUB_USER}/dotfiles.git > /dev/null 2>&1; then
    git clone https://github.com/${GITHUB_USER}/dotfiles.git $HOME/.dotfiles
  fi
fi

# Do the rest of the tasks from the home dir
cd $HOME

# create bindir
mkdir -p $HOME/bin

# Make passwordless sudo work
#export SUDO_ASKPASS=/bin/true

# A bit of a hack
mv .gitconfig .gitconfig.private
mv .bashrc .bashrc.dist
mv .zshrc .zshrc.dist
$HOME/.dotfiles.codespaces/bin/dotfiles.symlink install

# Setting proper terminal
if [[ -n "$FISH"  ]]; then
  echo "Setting shell to fish"
  sudo chsh -s /usr/bin/fish $USER
elif [[ -n "$ZSH" ]]; then
  echo "Setting shell to zsh"
  sudo chsh -s /usr/bin/zsh $USER
else
  echo "Setting shell to bash"
  sudo chsh -s /usr/bin/bash $USER
fi

# Install fzf
FZF_VERSION=0.30.0
echo "Install fzf to version 0.30.0"
curl -s -L https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION}-linux_amd64.tar.gz | tar xzC $HOME/bin

PATH=${PATH}:/opt/nvim/bin/

# Copy myRubbyRussell.zsh-theme to the themes directory
cp $HOME/.dotfiles.codespaces/zsh/myRobbyRussell.zsh-theme $HOME/.oh-my-zsh/themes

# Do the rest of the tasks from workspaces dir
cd /workspaces

# Symlink vscode workspaces file
ln -s $HOME/.dotfiles.codespaces/workspaces/rpcpool.code-workspace rpcpool.code-workspace

ADDITIONAL_REPOS="\
rpcpool/rpc-haproxy \
rpcpool/rpc-configurator \
rpcpool/Binaries-Ci \
rpcpool/nomad \
"

# Clone remaining repos
for repo in $ADDITIONAL_REPOS; do
  printf "Cloning %s\n" $repo
  git clone https://github.com/${repo}.git
done